### PR TITLE
Support for PostgreSQL uuid arrays #108

### PR DESCRIPTION
**Pull request by nls-jajuko**

### CODE REVIEW

**Comment by jampukka** [comment]
I'm guessing this works? :)

**Comment by nls-jajuko** [comment]
Testing . Forgot to add draft / work in progress

**Comment by nls-jajuko** [comment]
Basic support and GeoJSON output is OK. 
HTML does not work.

**Comment by jampukka** [comment]
Not sure how well other type of arrays work with HTML output anyways

**Comment by nls-jajuko** [comment]
HTML output fixes are out of scope for this issue.  #110 fixes those.

```
{
    "type": "Feature",
    "id": 1,
    "geometry": {
        "type": "Point",
        "coordinates": [
            23.9879801,
            68.4659627
        ]
    },
    "properties": {
        "uuid_arr": [
            "d5324c7e-6cfb-4e18-a565-f40b0ddb857b"
        ]
    }
}
```
I think this is OK now.

**Comment by nls-jajuko** [comment]
Should've been separate commits for fix and versions. Lesson learned. 
I will add separate fix to main

**Pull request merged**
